name: 'Get Project Version and Build Number'
description: 'Fetches tags and calculates version and build number from an INI file.'
inputs:
  BUILD_PREFIX:
    description: 'The semantic versioning prefix to apply to the build. (dev, alpha, beta, rc, etc)'
    required: true
  INI_FILE_PATH:
    description: 'Full path to the INI file including the workspace path.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        git fetch --tags
        $tags = git tag --sort=-v:refname
        
        $iniPath = "${{ inputs.INI_FILE_PATH }}"
        $content = Get-Content $iniPath -Raw       
        $semVerPattern = 'ProjectVersion=([0-9]+\.[0-9]+\.[0-9]+)'
        if ($content -match $semVerPattern) {
          $versionFromIni = $matches[1]
          echo "VERSION=$versionFromIni" >> $env:GITHUB_ENV
          
          $semVerTagPattern = '^(v)?[0-9]+\.[0-9]+\.[0-9]+'
          $latestTag = $null
          foreach ($tag in $tags) {
            if ($tag -match $semVerTagPattern) {
              $latestTag = $matches[0]
              break
            }
          }
          
          if ($null -eq $latestTag) {
            $latestTag = "0.0.0"
          } else {
            $latestTag = $latestTag -replace '^v', ''
          }
          
          $commitCount = & git rev-list --count "${latestTag}..HEAD"
          
          $newVersion = $versionFromIni
          if ($latestTag -ne "0.0.0" -and [Version]$latestTag -gt [Version]$versionFromIni) {
            $newVersion = $latestTag
          }
          
          $buildId = "$newVersion-${{ inputs.BUILD_PREFIX }}$commitCount"
          echo "BUILD_ID=$buildId" >> $env:GITHUB_ENV
        } else {
          Write-Error "Version not found in INI file."
          exit 1
        }
      shell: pwsh
